name: test-my-app
# the push flag tells the workflow to run each time a push is made to the repository
on: [push, workflow_dispatch] 
jobs:
  drive:
    # doesn't really matter what you run on, but ubuntu is the least resource intensive. UPDATE: windows will work the best for integreation tests. Not sure if linux is supported for integration tests.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    # this is the most important line. This runs all the files that are named *_test in the test folder
    - run: | # the pipe is used to run multiple commands. Apparently, its read as one command without the pipe. Im so sick of this.
        flutter config --enable-windows-desktop
        flutter test -d windows test/*_test.dart # this is for integration tests. It SHOULD run all the files that are named *_test in the test folder
